const projects = [
	{
		id: 0, 
		name: 'WhatsUp!', 
		description: 'Um app de conversas em grupos.', 
		category: 'Aplicativos',
		thumbnail: '',
		url: './assets/projects-img/img1.jpg',
		github: '',
	},
	{
		id: 1, 
		name: 'DevPost', 
		description: 'Um app de conversas em grupos.', 
		category: 'Aplicativos',
		thumbnail: '',
		url: './assets/projects-img/img2.jpg',
		github: '',
	},
	{
		id: 2, 
		name: 'Storage', 
		description: 'Um app de conversas em grupos.', 
		category: 'Aplicativos',
		thumbnail: '',
		url: './assets/projects-img/img3.jpg',
		github: '',
	},
	{
		id: 3, 
		name: 'FinançasApp', 
		description: 'Um app de conversas em grupos.', 
		category: 'Aplicativos',
		thumbnail: '',
		url: './assets/projects-img/img4.jpg',
		github: '',
	},
];